packages:
  - 'packages/*'
packages:
  - 'packages/*'  esNextPaths, es5Paths,
  esNextPaths,
} = require('./scripts/sharedshared/pathsByLanguageVersion');617703charset = utf-8confusing-browser-globals
es5Paths,
  esNextPaths, es5Paths,
